In [46]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
#? np.array() ==>> define nD array

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
type(A)

numpy.ndarray

In [49]:
A.shape
#? shape ==>> Dimensions of array

(2, 3)

In [50]:
x_t = np.array([1, 2, 3])
#? we can't do product to another matrices
x_t

array([1, 2, 3])

In [51]:
x = x_t.reshape(-1, 1)
#? by default np.array show to us x_t of a vector(1D array)
#? so we use from x.reshape(nOfRows, nOfColumns)
#? "nOfRows = -1" : means auto set num of rows
x

array([[1],
       [2],
       [3]])

In [52]:
x.shape

(3, 1)

In [53]:
x_t.shape

(3,)

In [54]:
x_t = x_t.reshape(1, -1)
x_t.shape

(1, 3)

In [55]:
x_t @ x
#? @ or .dot() use for multiplication matrix in python
#? .dot means dot product

array([[14]])

In [56]:
x_t.dot(x)

array([[14]])

In [57]:
y = x_t.dot(x)[0,0]
y

14

In [71]:
x_t * x

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [59]:
x_t

array([[1, 2, 3]])

In [60]:
x

array([[1],
       [2],
       [3]])

In [61]:
x @ x_t


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [62]:
4 * x

array([[ 4],
       [ 8],
       [12]])

In [63]:
x

array([[1],
       [2],
       [3]])

In [64]:
B = np.random.randint(1, 10, (3, 4))
#? random class .randint(start,end,(rows,columns))
B

array([[1, 6, 2, 8],
       [2, 1, 7, 4],
       [9, 7, 3, 7]])

In [67]:
C = A @ B
C

array([[32, 29, 25, 37],
       [68, 71, 61, 94]])

In [66]:
D = B @ A
#! m*n n*q

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [89]:
#? Next section An example for A and B to be movable and different


# Python Program illustrating
# numpy.cross() method
import numpy as np

# Vectors
a = np.array([3, 6])
b = np.array([9, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

# Cross product of vectors
print("\nCross product of vectors a and b =")
print(np.cross(a, b))

print("------------------------------------")

# Matrices
x = np.array([[2, 6, 9], [2, 7, 3]])
y = np.array([[7, 5, 6], [3, 12, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

# Cross product of matrices
print("\nCross product of matrices x and y =")
print(np.cross(x, y))

Vectors :
a =  [3 6]

b =  [ 9 10]

Cross product of vectors a and b =
-24
------------------------------------

Matrices :
x = [[2 6 9]
 [2 7 3]]

y = [[ 7  5  6]
 [ 3 12  3]]

Cross product of matrices x and y =
[[ -9  51 -32]
 [-15   3   3]]


In [88]:
# Python Program illustrating
# numpy.outer() method
import numpy as np

# Vectors
a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

# Outer product of vectors
print("\nOuter product of vectors a and b =")
print(np.outer(a, b))

print("------------------------------------")

# Matrices
x = np.array([[3, 6, 4], [9, 4, 6]])
y = np.array([[1, 15, 7], [3, 10, 8]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

# Outer product of matrices
print("\nOuter product of matrices x and y =")
print(np.outer(x, y))

Vectors :
a =  [2 6]

b =  [ 3 10]

Outer product of vectors a and b =
[[ 6 20]
 [18 60]]
------------------------------------

Matrices :
x = [[3 6 4]
 [9 4 6]]

y = [[ 1 15  7]
 [ 3 10  8]]

Outer product of matrices x and y =
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


In [87]:
# Python Program illustrating
# numpy.inner() method
import numpy as np

# Vectors
a = np.array([2, 6])
b = np.array([3, 10])
print("Vectors :")
print("a = ", a)
print("\nb = ", b)

# Inner Product of Vectors
print("\nInner product of vectors a and b =")
print(np.inner(a, b))

print("---------------------------------------")

# Matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)

# Inner product of matrices
print("\nInner product of matrices x and y =")
print(np.inner(x, y))


Vectors :
a =  [2 6]

b =  [ 3 10]

Inner product of vectors a and b =
66
---------------------------------------

Matrices :
x = [[2 3 4]
 [3 2 9]]

y = [[ 1  5  0]
 [ 5 10  3]]

Inner product of matrices x and y =
[[17 52]
 [13 62]]
