In [44]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
#? np.array() ==>> define nD array

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
type(A)


numpy.ndarray

In [47]:
A.shape
#? shape ==>> Dimensions of array

(2, 3)

In [48]:
x_t = np.array([1, 2, 3])
#? we can't do product to another matrices
x_t

array([1, 2, 3])

In [49]:
x = x_t.reshape(-1, 1)
#? by default np.array show to us x_t of a vector(1D array)
#? so we use from x.reshape(nOfRows, nOfColumns)
#? "nOfRows = -1" : means auto set num of rows
x

array([[1],
       [2],
       [3]])

In [50]:
x.shape

(3, 1)

In [51]:
x_t.shape

(3,)

In [52]:
x_t = x_t.reshape(1, -1)
x_t.shape

(1, 3)

In [53]:
x_t @ x
#? @ or .dot() use for multiplication matrix in python
#? .dot means dot product

array([[14]])

In [54]:
x_t.dot(x)

array([[14]])

In [55]:
y = x_t.dot(x)[0, 0]
y

14

In [56]:
x @ x_t

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [57]:
4 * x

array([[ 4],
       [ 8],
       [12]])

In [61]:
x

array([[1],
       [2],
       [3]])

In [74]:
B = np.random.randint(1, 10, (3, 4))
#? random class .randint(start,end,(rows,columns))
B

array([[7, 8, 4, 7],
       [8, 9, 1, 3],
       [1, 2, 6, 5]])

In [59]:
C = A @ B

In [60]:
D = B @ A
#! m*n n*q

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [ ]:
#? Next section An example for A and B to be movable and different