In [31]:
import numpy as np

a = np.array([1, 2, 3])
a.shape

(3,)

In [32]:
b = np.array([[1, 2, 3], [1, 2, 3]])
b.shape

(2, 3)

In [33]:
b.reshape(1, -1)

array([[1, 2, 3, 1, 2, 3]])

In [34]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
d


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
c == d[0:2, :]



array([[ True,  True,  True],
       [ True,  True,  True]])

In [37]:
np.all(a == b)

True

In [38]:
np.all([True, True, False])

False

In [39]:
np.any([True, True, False])

True

In [40]:
not np.any([True, True, False])

False

In [41]:
a = np.array([[1, 2], [2, 1]])
b = np.array([[4, 5], [5, 4]])
np.all(a @ b == b @ a)


True

In [42]:
a == a.T

array([[ True,  True],
       [ True,  True]])

In [43]:
A = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [1, 2, 3, 4]])
x = np.array([[10, 20, 30]])
x

array([[10, 20, 30]])

In [44]:
x.T

array([[10],
       [20],
       [30]])

In [66]:
A @ x.T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [70]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
A.trace()

6

In [73]:
x = np.array([[-1, 2, 5]])
x

array([[-1,  2,  5]])

In [75]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
A @ x.T

array([[18],
       [36]])

In [67]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 3, 4, 5], [1, -1, 3, 2], [-1, 3, 4, -5]])
A @ B

array([[ 1, 10, 22, -6],
       [ 7, 25, 55,  0]])

In [68]:
a = np.random.randint(0, 10, (10, 1))
a

array([[0],
       [6],
       [7],
       [2],
       [1],
       [7],
       [5],
       [1],
       [2],
       [1]])

In [69]:
one = np.ones((10, 1))
one

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
A = a @ one.T

In [ ]:
one @ a.T

In [ ]:
I = np.eye(10)
I

In [ ]:
np.all(A @ I == I @ A)

In [ ]:
np.all(A @ I == A)

In [48]:
d = np.diag(np.random.randint(1, 99, 10))
d

array([[14,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 65,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 35,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 93,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 96,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 38,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 84,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 47]])

In [53]:
x = np.random.randint(1, 10, (10, 1))
x

array([[1],
       [6],
       [8],
       [9],
       [8],
       [9],
       [8],
       [4],
       [4],
       [7]])

In [54]:
x.T

array([[1, 6, 8, 9, 8, 9, 8, 4, 4, 7]])

In [55]:
x.T.T

array([[1],
       [6],
       [8],
       [9],
       [8],
       [9],
       [8],
       [4],
       [4],
       [7]])

In [60]:
x_l2 = np.linalg.norm(x, 2)
my_x_l2 = np.sqrt(x.T @ x)

print(f'auto = {x_l2}, my = {my_x_l2}')

auto = 21.72556098240043, my = [[21.72556098]]


In [65]:
a = np.linalg.norm(x, 1)
a

64.0

In [64]:
b = np.linalg.norm(x, np.inf)
b

9.0