In [16]:
import numpy as np

A = np.array([[1, -1, 2], [4, 0, 6], [0, 1, -1]])
A

array([[ 1, -1,  2],
       [ 4,  0,  6],
       [ 0,  1, -1]])

In [13]:
#? rank of a matrix
np.linalg.matrix_rank(A)

3

In [18]:
#? det
A_det = np.linalg.det(A)
A_det

-2.0

In [19]:
#? inverse of a matrix
A_inv = np.linalg.inv(A)
A_inv

array([[ 3. , -0.5,  3. ],
       [-2. ,  0.5, -1. ],
       [-2. ,  0.5, -2. ]])

In [22]:
#? adj matrix = inv * det
A_inv * A_det

array([[-6.,  1., -6.],
       [ 4., -1.,  2.],
       [ 4., -1.,  4.]])